Farsh/Farsh/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from app.views import *
from Farsh import settings
from django.conf.urls.static import static
from django.contrib.auth import views as auth_views
from fa.views import *
urlpatterns = [

    url(r'^accounts/logout/$', auth_views.LogoutView.as_view(), name='logout'),
    url(r'^accounts/login/', auth_views.LoginView.as_view(template_name="login.html"), name="login"),
    url(r'^accounts/', include('django.contrib.auth.urls')),

    url(r'^admin/', admin.site.urls, name="admin"),
    url(r'^cart/$', sabad_kharid, name="cart"),

    url(r'^products/$', products, name="products"),
    url(r'^products/(?P<query>\w+)/$', products1, name="products"),
    url(r'^$', homepage, name="home"),
    url(r'^about_us', about_us, name="about_us"),

    url(r'^contact/$', contact_us, name="contact"),
    url(r'^signup/$', signup, name="signup"),

    url(r'^complaint/$', complaint, name="complaint"),
    url(r'^factor/$', factor, name="factor"),

    url(r'^order_registration/(?P<bag_id>\d+)/$', sabte_sefaresh, name="order_registration"),
    url(r'^update_address/(?P<bag_id>\d+)/$', update_address, name="update_address"),
    url(r'^^product_page/carpet/(?P<product_id>\d+)/$', product_page, name="product_page"),

    url(r'^search_result/$', search_result, name="search_result"),

    url(r'^order_track/$', peygiri_sefaresh, name="order_track"),
    url(r'^order/$', order, name="order"),

    url(r'^help/$', help, name="help"),
    url(r'^404/$', not_found, name="not_found"),
    url(r'^blog/post/(?P<post_id>[0-9]+)/?$', in_blog, name="in_blog"),
    url(r'^blog/$', blog, name="blog"),
    url(r'^order/remove/(?P<item_id>\d+)/$', remove_item, name="remove_item"),
    url(r'^profile/$', profile, name="profile"),
    url(r'^after_sabte_sefaresh/(?P<bag_id>\d+)/$', after_sabte_sefaresh, name="after_sabte_sefaresh"),

    # administratives #
    url(r'^administrator/$',administration,name='administratorhome'),
    url(r'^administrator/carpets/$', admin_carpets_index, name="admin_carpets"),
    url(r'^administrator/complaints/$', admin_complaints_index, name="admin_carpets"),
    url(r'^administrator/contact/$', admin_contacts_index, name="admin_carpets"),
    url(r'^administrator/carpet/create/$', admin_carpet_create,name='carpet_create'),
    url(r'^administrator/carpet/api/?$', Carpets.as_view()),
    url(r'^administrator/contact/api/?$', Contacts.as_view()),
    url(r'^administrator/complaint/api/?$', Complaints.as_view()),
    url(r'^administrator/carpet/api/(?P<carpet_id>[0-9]+)/?$', Carpets.as_view()),
    url(r'^administrator/contact/api/(?P<contact_id>[0-9]+)/?$', Contacts.as_view()),
    url(r'^administrator/complaint/api/(?P<complaint_id>[0-9]+)/?$', Complaints.as_view()),
    url(r'^administrator/carpet/update/(?P<pk>\d+)/$', admin_carpet_update, name='carpet_update'),
    url(r'^api/get_carpet_categories/', get_carpet_categories, name='get_carpet_categories'),
    url(r'^api/get_carpets/', get_carpets, name='get_carpets'),
    url(r'^administrator/carpet_categories/$',admin_carpet_categories_index),
    url(r'^administrator/carpet_category/create/$', admin_carpet_category_create,name='carpet_category_create'),
    url(r'^administrator/carpet_category/api/?$', CarpetCategories.as_view()),
    url(r'^administrator/carpet_category/api/(?P<category_id>[0-9]+)/?$', CarpetCategories.as_view()),
    url(r'^administrator/carpet_category/update/(?P<pk>\d+)/$', admin_carpet_category_update, name='carpet_category_update'),
    url(r'^administrator/user/$',admin_user_index),
    url(r'^administrator/user/create/$', register_admin,name='user_create'),
    url(r'^administrator/user/update/(?P<pk>\d+)/$', admin_user_update, name='user_update'),
    url(r'^administrator/user/api/?$', Users.as_view()),
    url(r'^administrator/user/api/(?P<user_id>[0-9]+)/?$', Users.as_view()),
    url(r'^fa/administrator/complaint/quick/answer/(?P<pk>\d+)/$', fa_admin_complaint_answer_quick_create, name='complaint_answer_quick'),
    url(r'^fa/administrator/text/complaint/(?P<pk>\d+)/$', text_complaint, name='text_complaint'),
    url(r'^fa/administrator/contact/quick/answer/(?P<pk>\d+)/$', fa_admin_contact_answer_quick_create, name='contact_answer_quick'),
    url(r'^fa/administrator/text/contact/(?P<pk>\d+)/$', text_contact, name='text_contact'),
    url(r'^administrator/post/$',fa_admin_post_index),
    url(r'^administrator/post/create/$', fa_admin_post_create,name='post_create'),
    url(r'^administrator/post/api/?$', Posts.as_view()),
    url(r'^administrator/post/api/(?P<post_id>[0-9]+)/?$', Posts.as_view()),
    url(r'^administrator/post/update/(?P<pk>\d+)/$', fa_admin_post_update, name='post_update'),
]
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

Farsh/app/models.py
from django.db import models
from django.contrib.auth.models import User
from django.db.models.signals import post_save
from django.dispatch import receiver
from multiselectfield import MultiSelectField

#todo: think for deletes

CARPET_SIZES = (("6 متری", "6 متری"), ("8 متری", "8 متری"), ("12 متری", "12 متری"), ("18 متری", "18 متری"), ("درخواستی", "درخواستی"))
TABLEAURUG_SIZE = (("100*150", "100*150"), ("70*100", "70*100"), ("50*100", "50*100"), ("50*70", "50*70"), ("درخواستی", "درخواستی"))
CARPET_COLORS = (("قرمز", "قرمز"), ("آبی", "آبی"), ("سرمه ای", "سرمه ای"), ("کرمی", "کرمی"), ("بنفش", "بنفش"), ("وارد-نشده", "وارد-نشده"))
BAG_STEPS = (("0", "پیش ثبت"), ("1", "ثبت سفارش"), ("2", "مرحله بافت"),("3", "مرحله تکمیل"), ("4", "تحویل به باربری" ), ("5", "تحویل به مشتری"))
POST_CATEGORY=(("خبری","خبری"),("علمی","علمی"),("صنعت","صنعت"),('دسته_بندی_نشده','دسته بندی نشده'))
# Create your models here.


class Profile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    full_name = models.CharField(max_length = 50, null=True, blank=True)
    phonenumber = models.CharField(max_length=15, null=True, blank=True)
    address = models.TextField(max_length=500, blank=True, default='----------')
    zip_code = models.CharField(max_length=10, blank=True, default='----------')

    def __str__(self):
        return "%s" % self.user.username

    def as_dict(self):
        return {
            "id": self.id,
            "Username": self.user.username,
            "Name": self.full_name,
            "Address": self.address,
            "ZipCode": self.zip_code,
            "PhoneNumber": self.phonenumber,
        }


@receiver(post_save, sender=User)
def update_user_profile(sender, instance, created, **kwargs):
    if created:
        Profile.objects.create(user=instance)
    instance.profile.save()


class CarpetCategory(models.Model):
    title = models.CharField(max_length=30, default="وارد نشده")
    category_parent = models.ForeignKey('self', blank=True, null=True, on_delete=models.PROTECT)
    image1 = models.ImageField(null=True, blank=True, upload_to='carpet-category/images/')
    image2 = models.ImageField(null=True, blank=True, upload_to='carpet-category/images/')

    def __str__(self):
        if self.category_parent:
            return "عنوان: %s / %s" % self.title,self.category_parent.title
        else:
            return "%s" % self.title

    def as_dict(self):
        # image1=""
        # image2=""
        # if self.image1:
        #     image1=self.image1.url
        # else:
        #     image1="بدون تصویر"
        # if self.image2:
        #     image2=self.image2.url
        # else:
        #     image2="بدون تصویر"

        if self.category_parent:
            p = self.category_parent.title
        else:
            p = 'ندارد'
        return {
            "id": self.id,
            "Title": self.title,
            "Parent": p,
            # "Image1": str(image1),
            # "Image2": str(image2)
        }


class Carpet(models.Model):
    title = models.CharField(max_length=30, default='وارد نشده')
    description = models.TextField(null=True, blank=True)
    category = models.ForeignKey(CarpetCategory, blank=True, null=True, on_delete=models.PROTECT)
    brush_num = models.PositiveIntegerField(default=0)
    density = models.PositiveIntegerField(default=0)
    colors_num = models.PositiveIntegerField(default=0)
    yarn_type = models.CharField(max_length=25, default='وارد نشده')
    wool_yarn_type = models.CharField(max_length=15, default='وارد نشده')
    yarn_height = models.FloatField(null=True, blank=True)
    antipilling = models.BooleanField(default=False)
    weight = models.PositiveIntegerField(default=0)
    guarantee_len = models.CharField(max_length=10, blank=True, default="وارد نشده")
    delivery_time = models.CharField(max_length=10, blank=True, default="وارد نشده")
    color = MultiSelectField(choices=CARPET_COLORS, null=True)
    size1 = models.CharField(max_length=20, choices=CARPET_SIZES, null=True, blank=True)
    price1 = models.PositiveIntegerField(default=0)
    size2 = models.CharField(max_length=20, choices=CARPET_SIZES, null=True, blank=True)
    price2 = models.PositiveIntegerField(default=0)
    size3 = models.CharField(max_length= 20, choices=CARPET_SIZES, null=True, blank=True)
    price3 = models.PositiveIntegerField(default=0)
    size4 = models.CharField(max_length= 20, choices=CARPET_SIZES, null=True, blank=True)
    price4 = models.PositiveIntegerField(default=0)
    size5 = models.CharField(max_length= 20, choices=CARPET_SIZES, null=True, blank=True)
    price5 = models.PositiveIntegerField(default=0)
    size6 = models.CharField(max_length= 20, choices=CARPET_SIZES, null=True, blank=True)
    price6 = models.PositiveIntegerField(default=0)
    image1 = models.ImageField(null=True, blank=True, upload_to='carpet/images/')
    image2 = models.ImageField(null=True, blank=True, upload_to='carpet/images/')
    image3 = models.ImageField(null=True, blank=True, upload_to='carpet/images/')
    image4 = models.ImageField(null=True, blank=True, upload_to='carpet/images/')
    image5 = models.ImageField(null=True, blank=True, upload_to='carpet/images/')
    image6 = models.ImageField(null=True, blank=True, upload_to='carpet/images/')
    image7 = models.ImageField(null=True, blank=True, upload_to='carpet/images/')
    image8 = models.ImageField(null=True, blank=True, upload_to='carpet/images/')
    admin_featured = models.BooleanField(default=False)
    admin_confirmed = models.BooleanField(default=False)

    def __str__(self):
            return "عنوان: %s / %s" % self.title,self.category.title

    def as_dict(self):
        if self.image1:
            image = self.image1.url
        else:
            image = "بدون تصویر"
        if self.category.category_parent:
            p = self.category.category_parent.title
        else:
            p = 'ندارد'
        return {
            "id": self.id,
            "Title": self.title,
            "Category": self.category.title,
            "Price1": self.price1,
            "Price2": self.price2,
            "Price3": self.price3,
            "Price4": self.price4,
            "Price5": self.price5,
            "Description": self.description,
            "CategoryParent": p,
            "Image": str(image),
            "Confirmed": str(self.admin_confirmed),
            "Featured": str(self.admin_featured),
        }


class TableauRugCategory(models.Model):
    title = models.CharField(max_length=30, default="وارد نشده")
    category_parent = models.ForeignKey('self', blank=True, null=True, on_delete=models.PROTECT)
    image1 = models.ImageField(null=True, upload_to='tableau-category/images/')
    image2 = models.ImageField(null=True, upload_to='tableau-category/images/')

    def __str__(self):
        if self.category_parent:
            return "عنوان: %s / %s" % self.title,self.category_parent.title
        else:
            return "%s" % self.title


class TableauRug(models.Model):

    title = models.CharField(max_length=30, default='وارد نشده')
    description = models.TextField(null=True, blank=True)
    category = models.ForeignKey(TableauRugCategory, null=True, on_delete=models.PROTECT)
    brush_num = models.PositiveIntegerField(default=0)
    guarantee_len = models.CharField(max_length=10, blank=True, default="وارد نشده")
    delivery_time = models.CharField(max_length=10, blank=True, default="وارد نشده")
    weight = models.PositiveIntegerField(default=0)
    size1 = models.CharField(max_length=20, choices=TABLEAURUG_SIZE, null=True, blank=True)
    price1 = models.PositiveIntegerField(default=0)
    size2 = models.CharField(max_length=10, choices=TABLEAURUG_SIZE, null=True, blank=True)
    price2 = models.PositiveIntegerField(default=0)
    size3 = models.CharField(max_length=20, choices=TABLEAURUG_SIZE, null=True, blank=True)
    price3 = models.PositiveIntegerField(default=0)
    size4 = models.CharField(max_length=20, choices=TABLEAURUG_SIZE, null=True, blank=True)
    price4 = models.PositiveIntegerField(default=0)
    size5 = models.CharField(max_length=20, choices=TABLEAURUG_SIZE, null=True, blank=True)
    price5 = models.PositiveIntegerField(default=0)
    size6 = models.CharField(max_length=20, choices=TABLEAURUG_SIZE, null=True, blank=True)
    price6 = models.PositiveIntegerField(default=0)
    image1 = models.ImageField(null=True, blank=True, upload_to='tableau/images/')
    image2 = models.ImageField(null=True, blank=True, upload_to='tableau/images/')
    image3 = models.ImageField(null=True, blank=True, upload_to='tableau/images/')
    image4 = models.ImageField(null=True, blank=True, upload_to='tableau/images/')
    image5 = models.ImageField(null=True, blank=True, upload_to='tableau/images/')
    image6 = models.ImageField(null=True, blank=True, upload_to='tableau/images/')
    image7 = models.ImageField(null=True, blank=True, upload_to='tableau/images/')
    image8 = models.ImageField(null=True, blank=True, upload_to='tableau/images/')
    admin_featured = models.BooleanField(default=False)
    admin_confirmed = models.BooleanField(default=False)


class OrderedItem(models.Model):

    item_carpet = models.ForeignKey(Carpet, null=True, blank=True, on_delete=models.PROTECT)
    item_tableau = models.ForeignKey(TableauRug, null=True, blank=True, on_delete=models.PROTECT)
    ordered_date = models.DateTimeField(auto_now_add=True)
    numbers = models.SmallIntegerField(default=0)
    color = models.CharField(max_length=10, null=True, blank=True)
    price = models.IntegerField(default=0)
    total_price = models.IntegerField(default=0, null=True)

    def __str__(self):
        if self.item_carpet:
            return "%s" % self.item_carpet
        else:
            return "%s" % self.item_tableau


class ShoppingBag(models.Model):

    owner = models.ForeignKey(User, null=True, on_delete=models.PROTECT)
    items = models.ManyToManyField(OrderedItem, blank=True)

Farsh/fa/templates/fa-administrator/fa-tableau/includes/owner_rental.html
{% load static %}
<div class="table-responsive">
    <table class="table table-bordered table-hover">
        <thead>
            <tr>
                <td class="text-right">نام کاربری</td>
                <td class="text-right">نام کامل</td>
                <td class="text-right">ایمیل</td>
                <td class="text-right">شماره تلفن</td>
                <td class="text-right">کد ملی</td>
                <td class="text-right">آدرس</td>
            </tr>
        </thead>
        <tbody>=
            <tr>
                <td class="text-right">{{rental_owner.username}}</td>
                <td class="text-right">{{rental_owner.profile.profile_fullname}}</td>
                <td class="text-right">{{rental_owner.profile.email1}}</td>
                <td class="text-right">{{rental_owner.profile.phonenumber}}</td>
                <td class="text-right">{{rental_owner.profile.profile_nid}}</td>
                <td class="text-right">{{rental_owner.profile.profile_address}}</td>
            </tr>
        </tbody>
    </table>
</div>

Farsh/fa/templates/fa-administrator/fa-tableau/includes/partial_carpet_form.html

{% load crispy_forms_tags %}
{% crispy form %}


Farsh/fa/templates/fa-administrator/fa-tableau/includes/partial_comment_create.html
{% load crispy_forms_tags %}
{% load static %}
<form method="post" enctype="multipart/form-data" action="/administrator/product/review/create/" class="js-comment-create-form">

    <div class="modal-header">
    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
    <h4 class="modal-title">ایجاد کامنت جدید</h4>

  </div>
    <div class="modal-body">
        <div class="row">
            <div class="col-xs-12 col-md-12">
            <div class="box box-warning">
                <div class="box-header with-border">
                    <h3 class="box-title">فرم ورود داده های کامنت جدید</h3>
                    <div class="box-tools pull-right">
                        <button type="button" class="btn btn-box-tool" data-widget="collapse"><i class="fa fa-minus"></i>
                        </button>

                    </div>
                </div>
                <div class="box-body">
                    <div class="row">
                        <div class="col-xs-12 col-md-12">
                            <div>
                                {% include 'fa-administrator/fa-comments/includes/partial_comment_form.html' %}
                            </div>
                            <div class="col-xs-12 col-sm-12 progress-container">
                                <div class="progress progress-striped active">
                                    <div class="progress-bar progress-bar-success" style="width:0%">

                                    </div>
                                </div>
                            </div>
                        </div>

                    </div>


                </div>
            </div>
        </div>

        </div>
        </div>

</form>
<script src="{% static 'fa/static/select2-4.0.3/dist/js/select2.min.js' %}"></script>

<script>

        $(function () {
            $('#id_review_user').select2({
                placeholder: 'شروع به تایپ حروف نام کاربری کنید...',
                dir:"RTL",
                language: {
                    noResults: function (params) {
                      return "نتیجه ای یافت نشد.";
                    }
                },
                escapeMarkup: function (markup) {
                  return markup;
                },
                ajax: {
                url: function (params) {

                return '/api/get_users/' + params.term;
            },
            dataType: 'json',
            delay: 250,
            processResults: function (data) {
                return {
                    results: data
                };
            },
            cache: true
            }
            });




        })
    </script>

<script>

        $(function () {
            $('#id_review_product').select2({
                placeholder: 'شروع به تایپ حروف نام کاربری کنید...',
                dir:"RTL",
                language: {
                    noResults: function (params) {
                      return "نتیجه ای یافت نشد.";
                    }
                },
                escapeMarkup: function (markup) {
                  return markup;
                },
                ajax: {
                url: function (params) {

                return '/api/get_carpets/' + params.term;
            },
            dataType: 'json',
            delay: 250,
            processResults: function (data) {
                return {
                    results: data
                };
            },
            cache: true
            }
            });




        })
    </script>

Farsh/fa/templates/fa-administrator/fa-tableau/includes/partial_comment_edit.html
{% load static %}
<form method="post" enctype="multipart/form-data" action="{% url 'review_product_update' form.instance.pk %}" class="js-comment-update-form">

  <div class="modal-header">
    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
    <h4 class="modal-title">به روز رسانی داده های کامنت</h4>
  </div>
  <div class="modal-body">
        <div class="row">
            <div class="col-xs-12 col-md-12">
            <div class="box box-warning">
                <div class="box-header with-border">
                    <h3 class="box-title">فرم کامنت</h3>
                    <div class="box-tools pull-right">
                        <button type="button" class="btn btn-box-tool" data-widget="collapse"><i class="fa fa-minus"></i>
                        </button>

                    </div>
                </div>
                <div class="box-body">
                    <div class="row">
                        <div class="col-xs-12 col-md-12">
                            <div>
                                {% include 'fa-administrator/fa-comments/includes/partial_comment_form.html' %}
                            </div>
                            <div class="col-xs-12 col-sm-12 progress-container">
                                <div class="progress progress-striped active">
                                    <div class="progress-bar progress-bar-success" style="width:0%">

                                    </div>
                                </div>
                            </div>
                        </div>

                    </div>


                </div>
            </div>
        </div>

        </div>
        </div>

  </div>

</form>
<script src="{% static 'fa/static/select2-4.0.3/dist/js/select2.min.js' %}"></script>

<script>

        $(function () {
            $('#id_review_user').select2({
                placeholder: 'شروع به تایپ حروف نام کاربری کنید...',
                dir:"RTL",
                language: {
                    noResults: function (params) {
                      return "نتیجه ای یافت نشد.";
                    }
                },
                escapeMarkup: function (markup) {
                  return markup;
                },
                ajax: {
                url: function (params) {

                return '/api/get_users/' + params.term;
            },
            dataType: 'json',
            delay: 250,
            processResults: function (data) {
                return {
                    results: data
                };
            },
            cache: true
            }
            });




        })
    </script>

<script>

        $(function () {
            $('#id_review_product').select2({
                placeholder: 'شروع به تایپ حروف نام کاربری کنید...',
                dir:"RTL",
                language: {
                    noResults: function (params) {
                      return "نتیجه ای یافت نشد.";
                    }
                },
                escapeMarkup: function (markup) {
                  return markup;
                },
                ajax: {
                url: function (params) {

                return '/api/get_products/' + params.term;
            },
            dataType: 'json',
            delay: 250,
            processResults: function (data) {
                return {
                    results: data
                };
            },
            cache: true
            }
            });




        })
    </script>

Farsh/fa/templates/fa-administrator/fa-tableau/includes/partial_comment_form.html

{% load crispy_forms_tags %}
{% crispy form %}


Farsh/fa/templates/fa-administrator/fa-tableau/includes/partial_rental_delete.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>

</body>
</html>

Farsh/fa/templates/fa-administrator/fa-tableau/includes/partial_tableau_create.html
{% load crispy_forms_tags %}
{% load static %}
<form method="post" enctype="multipart/form-data" action="/administrator/carpet/create/" class="js-carpet-create-form">

    <div class="modal-header">
    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
    <h4 class="modal-title">ایجاد محصول جدید</h4>

  </div>
    <div class="modal-body">

        <div class="row">
            <div class="col-xs-12 col-md-12">
            <div class="box box-warning">
                <div class="box-header with-border">
                    <h3 class="box-title">فرم ورود داده های محصول جدید</h3>
                    <div class="box-tools pull-right">
                        <button type="button" class="btn btn-box-tool" data-widget="collapse"><i class="fa fa-minus"></i>
                        </button>

                    </div>
                </div>
                <div class="box-body">
                    <div class="row">
                        <div class="col-xs-12 col-md-12">
                            <div>
                                {% include 'fa-administrator/fa-carpets/includes/partial_carpet_form.html' %}
                            </div>
                            <div class="col-xs-12 col-sm-12 progress-container">
                                <div class="progress progress-striped active">
                                    <div class="progress-bar progress-bar-success" style="width:0%">

                                    </div>
                                </div>
                            </div>
                        </div>

                    </div>


                </div>
            </div>
        </div>

        </div>
        </div>

</form>

<script src="{% static 'fa/static/select2-4.0.3/dist/js/select2.min.js' %}"></script>
<script src="{% static 'shared/plugins/ckeditor/ckeditor.js' %}"></script>
<script>

        $(function () {
            $('#id_category').select2({
                placeholder: 'شروع به تایپ حروف منطقه کنید...',
                dir:"RTL",
                ajax: {
                url: function (params) {

                return '/api/get_carpet_categories/' + params.term;
            },
            dataType: 'json',
            delay: 250,
            processResults: function (data) {
                return {
                    results: data
                };
            },
            cache: true
            }
            });




        })
    </script>

Farsh/fa/templates/fa-administrator/fa-tableau/includes/partial_tableau_edit.html
{% load static %}
<form method="post" enctype="multipart/form-data" action="{% url 'carpet_update' form.instance.pk %}" class="js-carpet-update-form">

  <div class="modal-header">
    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
    <h4 class="modal-title">به روز رسانی داده های دسته</h4>
  </div>
  <div class="modal-body">

        <div class="row">
            <div class="col-xs-12 col-md-12">
            <div class="box box-warning">
                <div class="box-header with-border">
                    <h3 class="box-title">فرم دسته</h3>
                    <div class="box-tools pull-right">
                        <button type="button" class="btn btn-box-tool" data-widget="collapse"><i class="fa fa-minus"></i>
                        </button>

                    </div>
                </div>
                <div class="box-body">
                    <div class="row">
                        <div class="col-xs-12 col-md-12">
                            <div>
                                {% include 'fa-administrator/fa-carpets/includes/partial_carpet_form.html' %}
                            </div>
                            <div class="col-xs-12 col-sm-12 progress-container">
                                <div class="progress progress-striped active">
                                    <div class="progress-bar progress-bar-success" style="width:0%">

                                    </div>
                                </div>
                            </div>
                        </div>

                    </div>


                </div>
            </div>
        </div>

        </div>
        </div>

  </div>

</form>
<script src="{% static 'fa/static/select2-4.0.3/dist/js/select2.min.js' %}"></script>
<script src="{% static 'shared/plugins/ckeditor/ckeditor.js' %}"></script>
<script>

        $(function () {
            $('#id_category_parent').select2({
                placeholder: 'شروع به تایپ حروف منطقه کنید...',
                dir:"RTL",
                ajax: {
                url: function (params) {

                return '/api/get_carpet_category/' + params.term;
            },
            dataType: 'json',
            delay: 250,
            processResults: function (data) {
                return {
                    results: data
                };
            },
            cache: true
            }
            });




        })
    </script>